/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateWorkflowTransitionDetailsScreen : The screen of the transition.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateWorkflowTransitionDetailsScreen {
    /// The ID of the screen.
    #[serde(rename = "id")]
    pub id: String,
}

impl CreateWorkflowTransitionDetailsScreen {
    /// The screen of the transition.
    pub fn new(id: String) -> CreateWorkflowTransitionDetailsScreen {
        CreateWorkflowTransitionDetailsScreen { id }
    }
}
