/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardGadgetSettingsPosition : The position of the gadget. When the gadget is placed into the position, other gadgets in the same column are moved down to accommodate it.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DashboardGadgetSettingsPosition {
    #[serde(rename = "The column position of the gadget.")]
    pub the_column_position_of_the_gadget_period: i32,
    #[serde(rename = "The row position of the gadget.")]
    pub the_row_position_of_the_gadget_period: i32,
}

impl DashboardGadgetSettingsPosition {
    /// The position of the gadget. When the gadget is placed into the position, other gadgets in the same column are moved down to accommodate it.
    pub fn new(
        the_column_position_of_the_gadget_period: i32,
        the_row_position_of_the_gadget_period: i32,
    ) -> DashboardGadgetSettingsPosition {
        DashboardGadgetSettingsPosition {
            the_column_position_of_the_gadget_period,
            the_row_position_of_the_gadget_period,
        }
    }
}
