/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// IssueLinkInwardIssue : Provides details about the linked issue. If presenting this link in a user interface, use the `inward` field of the issue link type to label the link.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IssueLinkInwardIssue {
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Box<crate::models::LinkedIssueFields>>,
    /// The ID of an issue. Required if `key` isn't provided.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The key of an issue. Required if `id` isn't provided.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The URL of the issue.
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
}

impl IssueLinkInwardIssue {
    /// Provides details about the linked issue. If presenting this link in a user interface, use the `inward` field of the issue link type to label the link.
    pub fn new() -> IssueLinkInwardIssue {
        IssueLinkInwardIssue {
            fields: None,
            id: None,
            key: None,
            param_self: None,
        }
    }
}
