/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// JiraExpressionsComplexityBeanSteps : The number of steps it took to evaluate the expression, where a step is a high-level operation performed by the expression. A step is an operation such as arithmetic, accessing a property, accessing a context variable, or calling a function.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JiraExpressionsComplexityBeanSteps {
    /// The maximum allowed complexity. The evaluation will fail if this value is exceeded.
    #[serde(rename = "limit")]
    pub limit: i32,
    /// The complexity value of the current expression.
    #[serde(rename = "value")]
    pub value: i32,
}

impl JiraExpressionsComplexityBeanSteps {
    /// The number of steps it took to evaluate the expression, where a step is a high-level operation performed by the expression. A step is an operation such as arithmetic, accessing a property, accessing a context variable, or calling a function.
    pub fn new(limit: i32, value: i32) -> JiraExpressionsComplexityBeanSteps {
        JiraExpressionsComplexityBeanSteps {
            limit,
            value,
        }
    }
}


