/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// JqlFunctionPrecomputationBean : Jql function precomputation.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JqlFunctionPrecomputationBean {
    #[serde(rename = "arguments", skip_serializing_if = "Option::is_none")]
    pub arguments: Option<Vec<String>>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(rename = "functionKey", skip_serializing_if = "Option::is_none")]
    pub function_key: Option<String>,
    #[serde(rename = "functionName", skip_serializing_if = "Option::is_none")]
    pub function_name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    #[serde(rename = "used", skip_serializing_if = "Option::is_none")]
    pub used: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl JqlFunctionPrecomputationBean {
    /// Jql function precomputation.
    pub fn new() -> JqlFunctionPrecomputationBean {
        JqlFunctionPrecomputationBean {
            arguments: None,
            created: None,
            field: None,
            function_key: None,
            function_name: None,
            id: None,
            operator: None,
            updated: None,
            used: None,
            value: None,
        }
    }
}
