/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// JqlFunctionPrecomputationUpdateBean : Precomputation id and its new value.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JqlFunctionPrecomputationUpdateBean {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "value")]
    pub value: String,
}

impl JqlFunctionPrecomputationUpdateBean {
    /// Precomputation id and its new value.
    pub fn new(id: i64, value: String) -> JqlFunctionPrecomputationUpdateBean {
        JqlFunctionPrecomputationUpdateBean {
            id,
            value,
        }
    }
}


