/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// NotificationRestrict : Restricts the notifications to users with the specified permissions.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotificationRestrict {
    /// List of groupId memberships required to receive the notification.
    #[serde(rename = "groupIds", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<Vec<String>>,
    /// List of group memberships required to receive the notification.
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<crate::models::GroupName>>,
    /// List of permissions required to receive the notification.
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<crate::models::RestrictedPermission>>,
}

impl NotificationRestrict {
    /// Restricts the notifications to users with the specified permissions.
    pub fn new() -> NotificationRestrict {
        NotificationRestrict {
            group_ids: None,
            groups: None,
            permissions: None,
        }
    }
}
