/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// NotificationEventTemplateEvent : The template of the event. Only custom events configured by Jira administrators have template.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotificationEventTemplateEvent {
    /// The description of the event.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The ID of the event. The event can be a [Jira system event](https://confluence.atlassian.com/x/8YdKLg#Creatinganotificationscheme-eventsEvents) or a [custom event](https://confluence.atlassian.com/x/AIlKLg).
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// The name of the event.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "templateEvent", skip_serializing_if = "Option::is_none")]
    pub template_event: Option<Box<crate::models::NotificationEventTemplateEvent>>,
}

impl NotificationEventTemplateEvent {
    /// The template of the event. Only custom events configured by Jira administrators have template.
    pub fn new() -> NotificationEventTemplateEvent {
        NotificationEventTemplateEvent {
            description: None,
            id: None,
            name: None,
            template_event: None,
        }
    }
}
